### ISSUE TITLE
Incorrect calc for Heapratio

### ISSUE THREAD

**Issue by lawtt** [Ericbla/check_jstat#11]
When calculating the heapmx I believe the calculation should be adding $ygcmx + $ogcmx.  When running this we are getting a false positive error stating we are using 147% of heap.

**Comment by solarisfire** [comment]
I have to second this. I was getting alerts for java using 195% of MaxHeapSize, with -Xmx2048m configured and less than 2GB being used. I have made the change so heapmx is now heapmx=$((($ygcmx + $ogcmx))), and these numbers look a lot more realistic.

**Comment by AlbertoArdu** [comment]
Endorsing previews comments.

**Comment by Ericbla** [comment]
Fixed by merging the PR #11
