### ISSUE TITLE
Wrong performance data format

### ISSUE THREAD

**Issue by danci1973** [Ericbla/check_jstat#3]
It seems that performance data is not in the expected 'Nagios Plugins' format, which is:

'label'=value[UOM];[warn];[crit];[min];[max]

https://www.monitoring-plugins.org/doc/guidelines.html#AEN200
http://docs.icinga.org/latest/en/perfdata.html#formatperfdata

This makes it hard to graph performance data with 'standard' tools (like pnp4nagios).

I don't see a need for PID in performance data output, so I would suggest this format (split into lines here for better view):

heap=heap-size-used(Bytes)
heap_max=heap-max-size(Bytes)
heap_ratio=%ratio;warning-threshold-%ratio;critical-threshold-%ratio
perm=perm-size-used(Bytes)
perm_max=perm-max-size(Bytes)
perm_ratio=%ratio;warning-threshold-%ratio;critical-threshold-%ratio

**Comment by Ericbla** [comment]
Seems now OK with contribution of dr4Ke in pull request: several check_jstat changes #9
