### ISSUE TITLE
/bin/bash instead /bin/sh

### ISSUE THREAD

**Issue by amarao** [Ericbla/check_jstat#7]
When /bin/sh used, script reports:

check_jstat.sh: 28: /usr/local/lib/nagios/plugins/check_jstat.sh: Syntax error: "(" unexpected

It should be '/bin/bash' in shebang.

Thanks.

**Comment by Ericbla** [comment]
Thanks for your interest for the project.
It was already fixed by @alexs77 pull-request #6 

I have also done the modification in check_of.sh script.

Both have now the shebang line:
```
#!/usr/bin/env bash
```
B.R.
